// templates/svelte-spa/src/App.svelte
<script lang="ts">
    let title = 'Welcome to your app';
</script>

<div class="app">
    <h1>{title}</h1>
    <p>Edit <code>src/App.svelte</code> and save to reload.</p>
</div>

<style>
    .app {
        max-width: 1280px;
        margin: 0 auto;
        padding: 2rem;
        text-align: center;
    }
</style>

// templates/vue-spa/src/App.vue
<script setup lang="ts">
const title = 'Welcome to your app';
</script>

<template>
    <div class="app">
        <h1>{{ title }}</h1>
        <p>Edit <code>src/App.vue</code> and save to reload.</p>
    </div>
</template>

<style scoped>
.app {
    max-width: 1280px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
}
</style>
